/* eslint-disable prettier/prettier */
import {createSlice} from '@reduxjs/toolkit';

export const languageSlice = createSlice({
  name: 'language',
  initialState: [
    {
      id: 1,
      title: 'English',
      selected: true,
      text: {
        dialogTitleText: 'Agreement',
        dialogBodyText:
          'I agree that my login data will be transferred to the UNITA SSO, under the UNITA GDPR Agreement that can be consulted here.',
        rememberChoiceText: 'Remember my choice',
        dialogDisagreeText: 'Disagree',
        dialogAgreeText: 'Agree',
      },
      contactText: {
        contactTitle: 'Contact us',
        coordinator: 'Coordinator',
        engineer: 'IT Engineer',
        team: 'Software development team',
      },
      poweredByText: 'Powered by',
      localLogin: 'Local Login',
      passwordMustMatch: 'Passwords must match',
      username: 'Username',
      password: 'Password',
      logIn: 'Log in',
      youDontHaveAnAccount: "You don't have an account?",
      register: 'Register',
      wrong: 'Wrong',
      close: 'close',
      passwordsMustMatch: 'Passwords must match.',
      firstName: 'First name',
      lastName: 'Last name',
      affiliation: 'Affiliation',
      rePassword: 'Re-password',
      pupil: 'Pupil',
      partner: 'Partner',
      other: 'Other',
      userExistsWithSame: 'User exists with same',
      logOut: 'Log Out',
      typeUser: 'User type',
      language: 'Language',
      dialogDisconnectWarning: 'Warning',
      dialogDisconnectText: 'You are about to leave this page, you will be logged out. Are you sure you want to leave?',
      dialogDisconnectDontQuit: 'Do not leave',
      dialogDisconnectQuit: 'Leave',
      drawerStudentCardTitle: 'My student card',
      expiredSessionToast: 'Your session has expired. You will be redirected in a few seconds to reconnect.',
    },
    {
      id: 2,
      title: 'Portuguese',
      selected: false,
      text: {
        dialogTitleText: 'Desacordo',
        dialogBodyText:
          'Concordo que meus dados de login serão transferidos para o SSO da UNITA, de acordo com o Acordo GDPR da UNITA, que pode ser consultado aqui.',
        rememberChoiceText: 'Lembre-se da minha escolha',
        dialogDisagreeText: 'Discordo',
        dialogAgreeText: 'Concordo',
      },
      contactText: {
        contactTitle: 'Contate-Nos',
        coordinator: 'Coordenador',
        engineer: 'Engenheiro de TI',
        team: 'Equipe de desenvolvimento de software',
      },
      poweredByText: 'Seu portal',
      localLogin: 'Login Local',
      passwordMustMatch: 'As senhas devem corresponder',
      username: 'Nombre de usuario',
      password: 'Senha',
      logIn: 'Conecte-se',
      youDontHaveAnAccount: 'Você não tem uma conta?',
      register: 'Registro',
      wrong: 'Errado',
      close: 'fechar',
      passwordsMustMatch: 'As senhas devem corresponder.',
      firstName: 'Primeiro nome',
      lastName: 'Último nome',
      affiliation: 'Afiliação',
      rePassword: 'Re-senha',
      pupil: 'Aluno',
      partner: 'Parceiro',
      other: 'De outros',
      userExistsWithSame: 'O usuário existe com o mesmo',
      logOut: 'Sair',
      typeUser: 'Tipo de usuário',
      language: 'Língua',
      dialogDisconnectWarning: 'Advertência',
      dialogDisconnectText: 'Está prestes a sair desta página, será desconectado. Tem a certeza de que quer sair?',
      dialogDisconnectDontQuit: 'Não sair',
      dialogDisconnectQuit: 'Sair',
      drawerStudentCardTitle: 'O meu cartão de estudante',
      expiredSessionToast: 'A sua sessão expirou. Será redireccionado dentro de alguns segundos para voltar a ligar.',
    },
    {
      id: 3,
      title: 'French',
      selected: false,
      text: {
        dialogTitleText: 'Entente',
        dialogBodyText:
          "J'accepte que mes données de connexion soient transférées à l'UNITA SSO, dans le cadre de l'UNITA GDPR Agreement qui peut être consulté ici.",
        rememberChoiceText: 'Souviens-toi de mon choix',
        dialogDisagreeText: 'Désaccord',
        dialogAgreeText: 'Accord',
      },
      contactText: {
        contactTitle: 'Contactez-nous',
        coordinator: 'Coordinateur',
        engineer: 'Ingénieur informatique',
        team: 'Equipe de développement logiciel',
      },
      poweredByText: 'Votre portail',
      localLogin: 'Connexion locale',
      passwordMustMatch: 'Les mots de passe doivent correspondre',
      username: "Nom d'utilisateur",
      password: 'Le mot de passe',
      logIn: 'Connexion',
      youDontHaveAnAccount: "Vous n'avez pas de compte?",
      register: "S'inscrire",
      wrong: 'Tort',
      close: 'fermer',
      passwordsMustMatch: 'Les mots de passe doivent correspondre.',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      affiliation: 'Affiliation',
      rePassword: 'Re-mot de passe',
      pupil: 'Élève',
      partner: 'Partenaire',
      other: 'Autre',
      userExistsWithSame: "L'utilisateur existe avec le même",
      logOut: 'Se déconnecter',
      typeUser: "Saisir l'utilisateur",
      language: 'Langue',
      dialogDisconnectWarning: 'Avertissement',
      dialogDisconnectText: 'Vous êtes sur le point de quitter cette page, vous allez être déconnecté. Êtes-vous sur de vouloir quitter?',
      dialogDisconnectDontQuit: 'Ne pas quitter',
      dialogDisconnectQuit: 'Quitter',
      drawerStudentCardTitle: 'Ma carte étudiante',
      expiredSessionToast: 'Votre session a expiré. Vous allez être redirigé dans quelques secondes pour pouvoir vous reconnecter.',
    },
    {
      id: 4,
      title: 'Romanian',
      selected: false,
      text: {
        dialogTitleText: 'Acord',
        dialogBodyText:
          'Sunt de acord ca datele mele de conectare sa fie transferate către UNITA SSO, în conformitate cu Acordul UNITA GDPR care poate fi consultat aici.',
        rememberChoiceText: 'Memorează-mi opțiunea',
        dialogDisagreeText: 'Dezacord',
        dialogAgreeText: 'Acord',
      },
      contactText: {
        contactTitle: 'Contactează-ne',
        coordinator: 'Coordonator',
        engineer: 'Inginer IT',
        team: 'Echipa de dezvoltare software',
      },
      poweredByText: 'Cu sprijinul ',
      localLogin: 'Autentificare locala',
      passwordMustMatch: 'Parolele trebuie sa fie identice',
      username: 'Nume utilizator',
      password: 'Parola',
      logIn: 'Logare',
      youDontHaveAnAccount: 'Nu aveti un cont?',
      register: 'Inregistrare',
      wrong: 'Gresit',
      close: 'inchis',
      passwordsMustMatch: 'Parolele trebuie sa se potriveasca.',
      firstName: 'Prenume:',
      lastName: 'Numele de familie',
      affiliation: 'Afiliere',
      rePassword: 'Parola rescrisa',
      pupil: 'Elev',
      partner: 'Partener',
      other: 'Altceva',
      userExistsWithSame: 'Exista utilizator cu acelasi ',
      logOut: 'Deconecare',
      typeUser: 'Tip utilizator',
      language: 'Limba',
      dialogDisconnectWarning: 'Avertizare',
      dialogDisconnectText: 'Sunteți pe cale să părăsiți această pagină, veți fi deconectat. Sunteți sigur că doriți să plecați?',
      dialogDisconnectDontQuit: 'Nu lăsați',
      dialogDisconnectQuit: 'Lăsați',
      drawerStudentCardTitle: 'Cardul meu de student',
      expiredSessionToast: 'Sesiunea dvs. a expirat. Veți fi redirecționat în câteva secunde pentru a vă reconecta.',
    },
    {
      id: 5,
      title: 'Italian',
      selected: false,
      text: {
        dialogTitleText: 'Accordo',
        dialogBodyText:
          "Accetto che i miei dati di accesso vengano trasferiti all'UNITA SSO, ai sensi dell'Accordo GDPR dell'UNITA che può essere consultato qui.",
        rememberChoiceText: 'Ricorda la mia scelta',
        dialogDisagreeText: 'Disaccetto',
        dialogAgreeText: 'Accetto',
      },
      contactText: {
        contactTitle: 'Contattaci',
        coordinator: 'Coordinatore',
        engineer: 'Ingegnere IT',
        team: 'Team di sviluppo software',
      },
      poweredByText: 'Il tuo portale',
      localLogin: 'Accesso locale',
      passwordMustMatch: 'Le password devono essere identiche',
      username: 'Nome utente',
      password: "Parola d'ordine",
      logIn: 'Accesso',
      youDontHaveAnAccount: 'Non hai un account?',
      register: 'Registrati',
      wrong: 'Sbagliato',
      close: 'chiudere',
      passwordsMustMatch: 'Le password devono essere identiche.',
      firstName: 'Nome di battesimo',
      lastName: 'Cognome',
      affiliation: 'Affiliazione',
      rePassword: 'Ri-password',
      pupil: 'Allievo',
      partner: 'Compagno',
      other: 'Altro',
      userExistsWithSame: "L'utente esiste con lo stesso",
      logOut: 'Disconnettersi',
      typeUser: 'Digita utente',
      language: 'Linguaggio',
      dialogDisconnectWarning: 'Attenzione',
      dialogDisconnectText: 'Stai per lasciare questa pagina, sarai disconnesso. Sei sicuro di voler uscire?',
      dialogDisconnectDontQuit: 'Non lasciare',
      dialogDisconnectQuit: 'Lasciare',
      drawerStudentCardTitle: 'La mia carta dello studente',
      expiredSessionToast: 'La tua sessione è scaduta. Sarai reindirizzato tra qualche secondo per riconnetterti.',
    },
    {
      id: 6,
      title: 'Spanish',
      selected: false,
      text: {
        dialogTitleText: 'Convenio',
        dialogBodyText:
          'Acepto que mis datos de inicio de sesión se transferirán al SSO de UNITA, en virtud del Acuerdo GDPR de UNITA que se puede consultar aquí.',
        rememberChoiceText: 'Recuerda mi elección',
        dialogDisagreeText: 'Disacepto',
        dialogAgreeText: 'Acepto',
      },
      contactText: {
        contactTitle: 'Contacta con nosotras',
        coordinator: 'Coordinador',
        engineer: 'Ingeniero informático',
        team: 'Equipo de desarrollo de software',
      },
      poweredByText: 'Tu portal',
      localLogin: 'Inicio de sesión local',
      passwordMustMatch: 'Las contraseñas deben coincidir',
      username: 'Nombre de usuario',
      password: 'Contraseña',
      logIn: 'Iniciar sesión',
      youDontHaveAnAccount: '¿No tienes una cuenta?',
      register: 'Registrarse',
      wrong: 'Incorrecto',
      close: 'cerrar',
      passwordsMustMatch: 'Las contraseñas deben coincidir.',
      firstName: 'Nombre de pila',
      lastName: 'Apellido',
      affiliation: 'Afiliación',
      rePassword: 'Cambiar contraseña',
      pupil: 'Alumno',
      partner: 'Pareja',
      other: 'Otro',
      userExistsWithSame: 'El usuario existe con el mismo',
      logOut: 'Cerrar sesión',
      typeUser: 'Tipo de usuario',
      language: 'Idioma',
      dialogDisconnectWarning: 'Advertencia',
      dialogDisconnectText: 'Está a punto de salir de esta página, se le cerrará la sesión. ¿Está seguro de que quiere salir?',
      dialogDisconnectDontQuit: 'No deje',
      dialogDisconnectQuit: 'Deje',
      drawerStudentCardTitle: 'Mi tarjeta de estudiante',
      expiredSessionToast: 'Su sesión ha expirado. Se le redirigirá en unos segundos para que se vuelva a conectar.',
    },
  ],
  reducers: {
    selectLanguage: (state, action) => {
      let oldLang = state.find(lang => lang.selected === true);
      oldLang.selected = false;
      let newLang = state.find(lang => lang.id === action.payload.id);
      newLang.selected = true;
    },
  },
});

export const {selectLanguage} = languageSlice.actions;

export default languageSlice.reducer;
