import { createSlice } from '@reduxjs/toolkit';

export const languageSlice = createSlice({
	name: 'language',
	initialState: [
		{ 
			id: 1, title: 'English', selected: true,
			text: {dialogTitleText: "Agreement", dialogBodyText: "I agree that my login data will be transferred to the UNITA SSO, under the UNITA GDPR Agreement that can be consulted here:", rememberChoiceText: "Remember my choice", dialogDisagreeText: "Disagree", dialogAgreeText: "Agree"},
			contactText: {contactTitle: "Contact us", coordinator: "Coordinator", engineer: "IT Engineer", team: "Software development team"},
			poweredByText: "Powered by", localLogin: "Local Login", passwordMustMatch: "Passwords must match",
			username: "Username", password: "Password", logIn: "Log in", youDontHaveAnAccount: "You don't have an account?", register: "Register",
			wrong:"Wrong", close: "close", passwordsMustMatch: "Passwords must match.", firstName: "First name", lastName: "Last name", affiliation: "Affiliation",
			rePassword: "Re-password", pupil: "Pupil", partner: "Partner", other: "Other", userExistsWithSame: "User exists with same", logOut: "Log Out", typeUser: "User type", language: "Language",
			support: "Support", service: "Service", serviceDescription: "The provider of technical support", wpDescription: "Contact people for possible developments / support",
			mobilityColumns: {"Institution" : "Institution", "Field (ISCED code)*" : "Field (ISCED code)*", "Name" : "Name", "EXPECTED UNITA STUDENTS (total)" : "EXPECTED UNITA STUDENTS (total)", "Slots for UBI" : "Slots for UBI", "Slots for UNIZAR" : "Slots for UNIZAR", "Slots for UPPA" : "Slots for UPPA", "Slots for USMB" : "Slots for USMB", "Slots for UNITO": "Slots for UNITO", "Slots for UVT" : "Slots for UVT", "UNITA STUDENTS N. - FIXED/FLEXIBLE" : "UNITA STUDENTS N. - FIXED/FLEXIBLE", "Study cycle (first, second, third cycle)" : "Study cycle (first, second, third cycle)", "VM students study cycle (first, second, third cycle)" : "VM students study cycle (first, second, third cycle)", "VM students specific degree/master degree program (if required by the course)" : "VM students specific degree/master degree program (if required by the course)", "VM students further requirements  (if required by the course)" : "VM students further requirements  (if required by the course)", "Language of instruction" : "Language of instruction", "Language requirements (level: B1, B2, C1, C2)" : "Language requirements (level: B1, B2, C1, C2)", "English friendly (optional) (Yes, No)" : "English friendly (optional) (Yes, No)", "ECTS" : "ECTS", "Semester (first/second/all year/both)" : "Semester (first/second/all year/both)", "Approximate starting period" : "Approximate starting period", "Approximate ending period" : "Approximate ending period", "Period (or date) for evaluations/examination" : "Period (or date) for evaluations/examination", "Asynchronous / Synchronous Course (optional)" : "Asynchronous / Synchronous Course (optional)", "Web Link to the description course" : "Web Link to the description course", "Contact of the course responsible" : "Contact of the course responsible", "Comments/Remarks" : "Comments/Remarks"},
			mobileApp: {linkText: "Mobile App", mobileVC: "Mobile Virtual Campus", buttonCaption: "To install the mobile app, please download the .apk file from the following link", QRCaption: "Or scan the following QR code"}
		},
		{ 
			id: 2, title: 'Portuguese', selected: false, 
			text: {dialogTitleText: "Acordo", dialogBodyText: "Concordo que meus dados de login serão transferidos para o SSO da UNITA, de acordo com o Acordo GDPR da UNITA, que pode ser consultado aqui:", rememberChoiceText: "Lembre-se da minha escolha", dialogDisagreeText: "Discordo", dialogAgreeText: "Concordo"}, 
			contactText: {contactTitle: "Contate-Nos", coordinator: "Coordenador", engineer: "Engenheiro de TI", team: "Equipe de desenvolvimento de software"}, 
			poweredByText: "Seu portal", localLogin: "Login Local", passwordMustMatch: "As senhas devem corresponder", 
			username: "Nombre de usuario", password: "Senha", logIn: "Conecte-se", youDontHaveAnAccount: "Você não tem uma conta?", register: "Registro", 
			wrong:"Errado", close: "fechar", passwordsMustMatch: "As senhas devem corresponder.", firstName: "Primeiro nome", lastName: "Último nome", affiliation: "Afiliação", 
			rePassword: "Re-senha", pupil: "Aluno", partner: "Parceiro", other: "De outros", userExistsWithSame: "O usuário existe com o mesmo", logOut: "Sair", typeUser: "Tipo de usuário", language: "Língua",
			support: "Suporte", service: "Serviço", serviceDescription: "O provedor de suporte técnico", wpDescription: "Entre em contato com as pessoas para possíveis desenvolvimentos/suporte",
			mobilityColumns: {"Institution" : "Instituição", "Field (ISCED code)*" : "Campo (código CITE)*", "Name" : "Nome", "EXPECTED UNITA STUDENTS (total)" : "ESTUDANTES UNITA ESPERADOS (total)", "Slots for UBI" : "Slots para UBI", "Slots for UNIZAR" : "Slots para UNIZAR", "Slots for UPPA" : "Slots para UPPA", "Slots for USMB" : "Slots para USMB", "Slots for UNITO": "Slots para UNITO", "Slots for UVT" : "Slots para UVT", "UNITA STUDENTS N. - FIXED/FLEXIBLE" : "UNITA ESTUDANTES N. - FIXO/FLEXÍVEL", "Study cycle (first, second, third cycle)" : "Ciclo de estudos (primeiro, segundo, terceiro ciclo)", "VM students study cycle (first, second, third cycle)" : "Ciclo de estudos dos alunos VM (primeiro, segundo, terceiro ciclo)", "VM students specific degree/master degree program (if required by the course)" : "Programa de graduação/mestrado específico para estudantes de VM (se exigido pelo curso)", "VM students further requirements  (if required by the course)" : "Requisitos adicionais dos alunos da VM (se exigido pelo curso)", "Language of instruction" : "Idioma das instruções", "Language requirements (level: B1, B2, C1, C2)" : "Requisitos de idioma (nível: B1, B2, C1, C2)", "English friendly (optional) (Yes, No)" : "Amigável em inglês (opcional) (Sim, Não)", "ECTS" : "ECTS", "Semester (first/second/all year/both)" : "Semestre (primeiro/segundo/todo o ano/ambos)", "Approximate starting period" : "Período inicial aproximado", "Approximate ending period" : "Período de término aproximado", "Period (or date) for evaluations/examination" : "Período (ou data) para avaliações/exame", "Asynchronous / Synchronous Course (optional)" : "Curso Assíncrono/Síncrono (opcional)", "Web Link to the description course" : "Link da Web para o curso de descrição", "Contact of the course responsible" : "Contato do responsável pelo curso", "Comments/Remarks" : "Comentários/Observações"},
			mobileApp: {linkText: "Aplicativo Móvel", mobileVC: "Campus Virtual Móvel", buttonCaption: "Para instalar o aplicativo móvel, faça o download do arquivo .apk no link a seguir", QRCaption: "Ou digitalize o seguinte código QR"}
		},
		{ 
			id: 3, title: 'French', selected: false, 
			text: {dialogTitleText: "Accord", dialogBodyText: "J'accepte que mes données de connexion soient transférées à l'UNITA SSO, dans le cadre de l'UNITA GDPR Agreement qui peut être consulté ici:", rememberChoiceText: "Souviens-toi de mon choix", dialogDisagreeText: "Désaccord", dialogAgreeText: "Accord"}, 
			contactText: {contactTitle: "Contactez-nous", coordinator: "Coordinateur", engineer: "Ingénieur informatique", team: "Equipe de développement logiciel"}, 
			poweredByText: "Votre portail", localLogin: "Connexion locale", passwordMustMatch: "Les mots de passe doivent correspondre", 
			username: "Nom d'utilisateur", password: "Le mot de passe", logIn: "Connexion", youDontHaveAnAccount: "Vous n'avez pas de compte?", register: "S'inscrire", 
			wrong:"Tort", close: "proche", passwordsMustMatch: "Les mots de passe doivent correspondre.", firstName: "Prénom", lastName: "Nom de famille", affiliation: "Affiliation", 
			rePassword: "Re-mot de passe", pupil: "Élève", partner: "Partenaire", other: "Autre", userExistsWithSame: "L'utilisateur existe avec le même", logOut: "Se déconnecter", typeUser: "Saisir l'utilisateur", language: "Langue",
			support: "Support", service: "Service", serviceDescription: "Le fournisseur de support technique", wpDescription: "Personnes de contact pour d'éventuels développements / support",
			mobilityColumns: {"Institution" : "Institution", "Field (ISCED code)*" : "Champ (code ISCED)*", "Name" : "Nom", "EXPECTED UNITA STUDENTS (total)" : "ÉTUDIANTS UNITA ATTENDUS (total)", "Slots for UBI" : "Slots pour UBI", "Slots for UNIZAR" : "Slots pour UNIZAR", "Slots for UPPA" : "Des créneaux pour l'UPPA", "Slots for USMB" : "Slots pour USMB", "Slots for UNITO": "Slots pour UNITO", "Slots for UVT" : "Slots pour UVT", "UNITA STUDENTS N. - FIXED/FLEXIBLE" : "UNITA ÉTUDIANTS N. - FIXE/FLEXIBLE", "Study cycle (first, second, third cycle)" : "Cycle d'études (premier, deuxième, troisième cycle)", "VM students study cycle (first, second, third cycle)" : "Cycle d'études des étudiants VM (premier, deuxième, troisième cycle)", "VM students specific degree/master degree program (if required by the course)" : "Programme de diplôme / master spécifique aux étudiants VM (si requis par le cours)", "VM students further requirements  (if required by the course)" : "Exigences supplémentaires des étudiants VM (si requis par le cours)", "Language of instruction" : "Langue d'enseignement", "Language requirements (level: B1, B2, C1, C2)" : "Exigences linguistiques (niveau: B1, B2, C1, C2)", "English friendly (optional) (Yes, No)" : "Anglais amical (facultatif) (Oui, Non)", "ECTS" : "ECTS", "Semester (first/second/all year/both)" : "Semestre (premier/deuxième/toute l'année/les deux)", "Approximate starting period" : "Période de démarrage approximative", "Approximate ending period" : "Période de fin approximative", "Period (or date) for evaluations/examination" : "Période (ou date) pour les évaluations/examens", "Asynchronous / Synchronous Course (optional)" : "Cours asynchrone / synchrone (optionnel)", "Web Link to the description course" : "Lien Web vers la description du cours", "Contact of the course responsible" : "Contact du responsable du cours", "Comments/Remarks" : "Commentaires/Remarques"},
			mobileApp: {linkText: "Application Mobile", mobileVC: "Campus Virtuel Mobile", buttonCaption: "Pour installer l'application mobile, veuillez télécharger le fichier .apk à partir du lien suivant", QRCaption: "Ou scannez le code QR suivant"}
		},
		{
			id: 4, title: 'Romanian', selected: false, 
			text: {dialogTitleText: "Acord", dialogBodyText: "Sunt de acord ca datele mele de conectare sa fie transferate către UNITA SSO, în conformitate cu Acordul UNITA GDPR care poate fi consultat aici:", rememberChoiceText: "Memorează-mi opțiunea", dialogDisagreeText: "Dezacord", dialogAgreeText: "Acord"}, 
			contactText: {contactTitle: "Contactează-ne", coordinator: "Coordonator", engineer: "Inginer IT", team: "Echipa de dezvoltare software"}, 
			poweredByText: "Cu sprijinul ", localLogin: "Autentificare locala", passwordMustMatch: "Parolele trebuie sa fie identice", 
			username: "Nume utilizator", password: "Parola", logIn: "Logare", youDontHaveAnAccount: "Nu aveti un cont?", register: "Inregistrare", 
			wrong:"Gresit", close: "inchis", passwordsMustMatch: "Parolele trebuie sa se potriveasca.", firstName: "Prenume:", lastName: "Numele de familie", affiliation: "Afiliere", 
			rePassword: "Parola rescrisa", pupil: "Elev", partner: "Partener", other: "Altceva", userExistsWithSame: "Exista utilizator cu acelasi ", logOut: "Deconectare", typeUser: "Tip utilizator", language: "Limba",
			support: "Suport", service: "Serviciu", serviceDescription: "Furnizorul de suport tehnic", wpDescription: "Oameni de contact pentru posibile dezvoltări / suport",
			mobilityColumns: {"Institution" : "Instituția", "Field (ISCED code)*" : "Câmp (cod ISCED)*", "Name" : "Nume", "EXPECTED UNITA STUDENTS (total)" : "STUDENTI ACCEPTAȚI UNITA (total)", "Slots for UBI" : "Sloturi pentru UBI", "Slots for UNIZAR" : "Sloturi pentru UNIZAR", "Slots for UPPA" : "Sloturi pentru UPPA", "Slots for USMB" : "Sloturi pentru USMB", "Slots for UNITO": "Sloturi pentru UNITO", "Slots for UVT" : "Sloturi pentru UVT", "UNITA STUDENTS N. - FIXED/FLEXIBLE" : "STUDENȚI UNITA N. - FIX/FLEXIBIL", "Study cycle (first, second, third cycle)" : "Ciclul de studiu (primul, al doilea, al treilea ciclu)", "VM students study cycle (first, second, third cycle)" : "Studenții VM ciclul de studiu (primul, al doilea, al treilea ciclu)", "VM students specific degree/master degree program (if required by the course)" : "Programul de licență/masterat specific studenților VM (dacă este cerut de curs)", "VM students further requirements  (if required by the course)" : "Cerințe suplimentare studenților VM (dacă sunt cerute de curs)", "Language of instruction" : "Limba de studiu", "Language requirements (level: B1, B2, C1, C2)" : "Cerințe lingvistice (nivel: B1, B2, C1, C2)", "English friendly (optional) (Yes, No)" : "Limba engleză (opțional) (Da, Nu)", "ECTS" : "ECTS", "Semester (first/second/all year/both)" : "Semestrul (primul/al doilea/tot anul/ambele)", "Approximate starting period" : "Perioada aproximativă de începere", "Approximate ending period" : "Perioada aproximativă de încheiere", "Period (or date) for evaluations/examination" : "Perioada (sau data) pentru evaluări/examinare", "Asynchronous / Synchronous Course (optional)" : "Curs asincron / sincron (opțional)", "Web Link to the description course" : "Link Web pentru descrierea cursului", "Contact of the course responsible" : "Contact responsabil de curs", "Comments/Remarks" : "Comentarii/Observații"},
			mobileApp: {linkText: "Aplicație Mobilă", mobileVC: "Campus Virtual Mobil", buttonCaption: "Pentru a instala aplicația mobilă, vă rugăm să descărcați fișierul .apk de la următorul link", QRCaption: "Sau scanați următorul cod QR"}
		},
		{
			id: 5, title: 'Italian', selected: false, 
			text: {dialogTitleText: "Accordo", dialogBodyText: "Accetto che i miei dati di accesso vengano trasferiti all'UNITA SSO, ai sensi dell'Accordo GDPR dell'UNITA che può essere consultato qui:", rememberChoiceText: "Ricorda la mia scelta", dialogDisagreeText: "Disaccetto", dialogAgreeText: "Accetto"}, 
			contactText: {contactTitle: "Contattaci", coordinator: "Coordinatore", engineer: "Ingegnere IT", team: "Team di sviluppo software"}, 
			poweredByText: "Il tuo portale", localLogin: "Accesso locale", passwordMustMatch: "Le password devono essere identiche", 
			username: "Nome utente", password: "Parola d'ordine", logIn: "Accesso", youDontHaveAnAccount: "Non hai un account?", register: "Registrati", 
			wrong:"Sbagliato", close: "chiudere", passwordsMustMatch: "Le password devono essere identiche.", firstName:"Nome di battesimo", lastName: "Cognome", affiliation: "Affiliazione", 
			rePassword: "Ri-password", pupil: "Allievo", partner: "Compagno", other: "Altro", userExistsWithSame: "L'utente esiste con lo stesso", logOut: "Disconnettersi", typeUser: "Digita utente", language: "Linguaggio",
			support: "Supporto", service: "Servizio", serviceDescription: "Il fornitore del supporto tecnico", wpDescription: "Contattare le persone per possibili sviluppi/supporto",
			mobilityColumns: {"Institution" : "Istituzione", "Field (ISCED code)*" : "Campo (codice ISCED)*", "Name" : "Nome", "EXPECTED UNITA STUDENTS (total)" : "STUDENTI ATTESI DELL'UNITA (totale)", "Slots for UBI" : "Slot per UBI", "Slots for UNIZAR" : "Slot per UNIZAR", "Slots for UPPA" : "Slot per UPPA", "Slots for USMB" : "Slot per USMB", "Slots for UNITO": "Slot per UNITO", "Slots for UVT" : "Slot per UVT", "UNITA STUDENTS N. - FIXED/FLEXIBLE" : "UNITA STUDENTI N. - FISSO/FLESSIBILE", "Study cycle (first, second, third cycle)" : "Ciclo di studio (primo, secondo, terzo ciclo)", "VM students study cycle (first, second, third cycle)" : "Ciclo di studio studenti VM (primo, secondo, terzo ciclo)", "VM students specific degree/master degree program (if required by the course)" : "Corso di laurea magistrale/laurea magistrale studenti VM (se previsto dal corso)", "VM students further requirements  (if required by the course)" : "Ulteriori requisiti studenti VM (se previsti dal corso)", "Language of instruction" : "Lingua di istruzione", "Language requirements (level: B1, B2, C1, C2)" : "Requisiti linguistici (livello: B1, B2, C1, C2)", "English friendly (optional) (Yes, No)" : "Inglese amichevole (opzionale) (Sì, No)", "ECTS" : "ECTS", "Semester (first/second/all year/both)" : "Semestre (primo/secondo/tutto l'anno/entrambi)", "Approximate starting period" : "Periodo di inizio approssimativo", "Approximate ending period" : "Periodo di fine approssimativo", "Period (or date) for evaluations/examination" : "Periodo (o data) per valutazioni/esami", "Asynchronous / Synchronous Course (optional)" : "Corso asincrono/sincrono (opzionale)", "Web Link to the description course" : "Link Web alla descrizione del corso", "Contact of the course responsible" : "Contatto del responsabile del corso", "Comments/Remarks" : "Commenti/Osservazioni"},
			mobileApp: {linkText: "App Mobile", mobileVC: "Campus Virtuale Mobile", buttonCaption: "Per installare l'app mobile, si prega di scaricare il file .apk dal seguente link", QRCaption: "Oppure scansiona il seguente codice QR"}
		},
		{
			id: 6, title: 'Spanish', selected: false, 
			text: {dialogTitleText: "Convenio", dialogBodyText: "Acepto que mis datos de inicio de sesión se transferirán al SSO de UNITA, en virtud del Acuerdo GDPR de UNITA que se puede consultar aquí:", rememberChoiceText: "Recuerda mi elección", dialogDisagreeText: "Disacepto", dialogAgreeText: "Acepto"}, 
			contactText: {contactTitle: "Contacta con nosotras", coordinator: "Coordinador", engineer: "Ingeniero informático", team: "Equipo de desarrollo de software"}, 
			poweredByText: "Tu portal", localLogin: "Inicio de sesión local", passwordMustMatch: "Las contraseñas deben coincidir", 
			username: "Nombre de usuario", password: "Contraseña", logIn: "Iniciar sesión", youDontHaveAnAccount: "¿No tienes una cuenta?", register: "Registrarse", 
			wrong:"Incorrecto", close: "cerrar", passwordsMustMatch: "Las contraseñas deben coincidir.", firstName:"Nombre de pila", lastName: "Apellido", affiliation: "Afiliación", 
			rePassword: "Cambiar contraseña", pupil: "Alumno", partner: "Pareja", other: "Otro", userExistsWithSame: "El usuario existe con el mismo", logOut: "Cerrar sesión", typeUser: "Tipo de usuario", language: "Idioma",
			support: "Soporte", service: "Servicio", serviceDescription: "El proveedor de soporte técnico", wpDescription: "Personas de contacto para posibles desarrollos/soporte",
			mobilityColumns: {"Institution" : "Institución", "Field (ISCED code)*" : "Campo (código CINE)*", "Name" : "Nombre", "EXPECTED UNITA STUDENTS (total)" : "ESTUDIANTES UNITA ESPERADOS (total)", "Slots for UBI" : "Ranuras para UBI", "Slots for UNIZAR" : "Ranuras para UNIZAR", "Slots for UPPA" : "Ranuras para UPPA", "Slots for USMB" : "Ranuras para USMB", "Slots for UNITO": "Ranuras para UNITO", "Slots for UVT" : "Ranuras para UVT", "UNITA STUDENTS N. - FIXED/FLEXIBLE" : "ESTUDIANTES UNITA N. - FIJO / FLEXIBLE", "Study cycle (first, second, third cycle)" : "Ciclo de estudios (primero, segundo, tercer ciclo)", "VM students study cycle (first, second, third cycle)" : "Alumnos VM estudian ciclo (primero, segundo, tercer ciclo)", "VM students specific degree/master degree program (if required by the course)" : "Programa de grado/maestría específico para estudiantes de VM (si el curso lo requiere)", "VM students further requirements  (if required by the course)" : "Requisitos adicionales de los estudiantes de VM (si el curso lo requiere)", "Language of instruction" : "Lenguaje de instrucción", "Language requirements (level: B1, B2, C1, C2)" : "Requisitos de idioma (nivel: B1, B2, C1, C2)", "English friendly (optional) (Yes, No)" : "Inglés amigable (opcional) (Sí, No)", "ECTS" : "ECTS", "Semester (first/second/all year/both)" : "Semestre (primero/segundo/todo el año/ambos)", "Approximate starting period" : "Período de inicio aproximado", "Approximate ending period" : "Periodo final aproximado", "Period (or date) for evaluations/examination" : "Período (o fecha) para evaluaciones/examen", "Asynchronous / Synchronous Course (optional)" : "Curso Asíncrono / Sincrónico (opcional)", "Web Link to the description course" : "Enlace web a la descripción del curso", "Contact of the course responsible" : "Contacto del responsable del curso", "Comments/Remarks" : "Comentarios/Observaciones"},
			mobileApp: {linkText: "Aplicación Movil", mobileVC: "Campus Virtual Móvil", buttonCaption: "Para instalar la aplicación móvil, descargue el archivo .apk desde el siguiente enlace", QRCaption: "O escanea el siguiente código QR"}
		}
	],
	reducers: {
		selectLanguage: (state, action) => {
			let oldLang = state.find(lang => lang.selected === true);
			oldLang.selected = false;
			let newLang = state.find(lang => lang.id === action.payload.id);
			newLang.selected = true;
			localStorage.setItem("language", newLang.id);
		},
	},
});

export const { selectLanguage } = languageSlice.actions;

export default languageSlice.reducer;